name: mayfly

services:
    be:
        build:
            context: .
            dockerfile: Dockerfile
            target: be
        environment:
            - NODE_ENV=production
        ports:
            - "1337:1337"
        networks:
            - app

    fe:
        build:
            context: .
            dockerfile: Dockerfile
            target: fe
        environment:
            - NODE_ENV=production
        ports:
            - "80:80"
        networks:
            - app

networks:
    app:
        driver: bridge
