name: mayfly

services:
    be:
        build:
            context: .
            dockerfile: Dockerfile
            target: be
        env_file:
            - .env
        environment:
            - NODE_ENV=production
        ports:
            - "1337:1337"
        depends_on:
            - db
        networks:
            - app

    fe:
        build:
            context: .
            dockerfile: Dockerfile
            target: fe
        environment:
            - NODE_ENV=production
        ports:
            - "80:80"
        networks:
            - app

    db:
        image: informaticsmatters/rdkit-cartridge-debian
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - app

networks:
    app:
        driver: bridge

volumes:
    postgres_data:
