/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as ReagentsListImport } from "./routes/reagentsList";
import { Route as IndexImport } from "./routes/index";

// Create/Update Routes

const ReagentsListRoute = ReagentsListImport.update({
    path: "/reagentsList",
    getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
    path: "/",
    getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
    interface FileRoutesByPath {
        "/": {
            id: "/";
            path: "/";
            fullPath: "/";
            preLoaderRoute: typeof IndexImport;
            parentRoute: typeof rootRoute;
        };
        "/reagentsList": {
            id: "/reagentsList";
            path: "/reagentsList";
            fullPath: "/reagentsList";
            preLoaderRoute: typeof ReagentsListImport;
            parentRoute: typeof rootRoute;
        };
    }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
    "/": typeof IndexRoute;
    "/reagentsList": typeof ReagentsListRoute;
}

export interface FileRoutesByTo {
    "/": typeof IndexRoute;
    "/reagentsList": typeof ReagentsListRoute;
}

export interface FileRoutesById {
    __root__: typeof rootRoute;
    "/": typeof IndexRoute;
    "/reagentsList": typeof ReagentsListRoute;
}

export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath;
    fullPaths: "/" | "/reagentsList";
    fileRoutesByTo: FileRoutesByTo;
    to: "/" | "/reagentsList";
    id: "__root__" | "/" | "/reagentsList";
    fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
    IndexRoute: typeof IndexRoute;
    ReagentsListRoute: typeof ReagentsListRoute;
}

const rootRouteChildren: RootRouteChildren = {
    IndexRoute: IndexRoute,
    ReagentsListRoute: ReagentsListRoute,
};

export const routeTree = rootRoute
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes<FileRouteTypes>();

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/reagentsList"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/reagentsList": {
      "filePath": "reagentsList.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
