import { z } from "zod";
import { BaseSearchSchema } from "../baseSchemas";

const SearchFieldEnum = z.enum([
    "name",
    "room",
    "structure",
    "cas",
    "producer",
    "catalogId",
    "catalogLink",
]);

// THIS SCHEMA IS USED TILL REPLACEMENT IS FOUND IN AUTOGENERATED SCHEMAS
export const ReagentSearchSchema = BaseSearchSchema.extend({
    sortBy: z
        .enum([
            "name",
            "description",
            "structure",
            "category",
            "quantity",
            "status",
            "expirationDate",
            "storageLocation",
            "cas",
            "producer",
            "catalogId",
            "catalogLink",
            "pricePerUnit",
            "createdAt",
            "updatedAt",
        ])
        .default("name"),
    searchBy: z
        .union([
            z.array(SearchFieldEnum), // array allows for multiple items selection
            SearchFieldEnum,
        ])
        .transform((val) => (Array.isArray(val) ? val : [val]))
        .optional(), // output array of strings or a array with a single string
    category: z.enum(["sample", "reagent"]).optional(),
    status: z.enum(["available", "lowStock", "outOfStock", "ordered", "notAvailable"]).optional(),
    storageLocation: z.string().optional(),
});

export type ReagentSearch = z.infer<typeof ReagentSearchSchema>;
