openapi: 3.0.0
info:
  title: Luna API
  version: 1.0.0
paths:
  /reagents:
    get:
      tags:
        - "Reagents"  # Only include the tag name here
      summary: Get all reagents
      description: Fetch all reagents from the database.
      operationId: getReagents  # Adding an operationId can help in displaying correctly
      responses:
        '200':
          description: Returns an array of reagents
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Reagent'

components:
  schemas:
    Reagent:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        category:
          type: string
          enum:
            - REAGENT
            - SAMPLE
        structure:
          type: string
        description:
          type: string
          nullable: true
        quantityLeft:
          type: number
        unit:
          type: string
        size:
          type: number
          nullable: true
        expirationDate:
          type: string
          format: date-time
          nullable: true
        storageLocation:
          type: string
        casNumber:
          type: string
          nullable: true
        producer:
          type: string
          nullable: true
        catalogId:
          type: string
          nullable: true
        catalogLink:
          type: string
          format: uri
          nullable: true
        pricePerUnit:
          type: number
          nullable: true
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

