name: "Auto Assign"
on:
    pull_request:
        types: [opened]

jobs:
    code-review:
        permissions:
            contents: read
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Auto-assign reviewers
              uses: ./.github/actions/auto-add-reviewers
              with:
                  configuration-path: ".github/auto_assign.yml"
