name: "Auto Assign"
on:
    pull_request:
        types: [opened]

jobs:
    code-review:
        permissions:
            contents: read
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - id: labeler
              uses: actions/labeler@v5

            - uses: actions/checkout@v4

            - name: Auto-assign for FE
              uses: ./.github/actions/auto-add-reviewers
              with:
                  configuration-path: ".github/auto_assign.yaml"
